
chat_prefix: "<rank> &x&6&4&d&7&5&e<name> &x&d&5&f&f&e&c: &x&b&4&b&d&d&7<messages>"
facebook_URL: "https://fb.com/mcsiamcraft"
discord_URL: "https://discord.gg/KASBrBTR2X"

spawn:
  world: SCLobby
  x: -18.5
  y: 86.5
  z: -251.5
  yaw: 0.0
  pitch: 0.0

item_join:
  item-1:
    material: CLOCK
    slot: 0
    amount: 1
    displayName: "&x&f&f&9&f&3&c&l▸ &x&6&b&e&e&7&cServer Selector &x&f&f&9&f&3&c&l◂"
    lore: []
  item-2:
    material: DIAMOND_SWORD
    slot: 7
    amount: 1
    displayName: "&x&f&f&9&f&3&c&l▸ &x&6&b&e&e&7&cPvp Mode &x&f&f&9&f&3&c&l◂"
    lore: []

item_pvp:
  item_1:
    material: DIAMOND_SWORD
    slot: 7
    amount: 1
    displayName: "&x&f&f&9&f&3&c&l▸ &x&6&b&e&e&7&cPvp Mode &x&f&f&9&f&3&c&l◂"
    enchantments:
      - "damage_all:1"
    lore: []
  item_2:
    material: DIAMOND_HELMET
    slot: HELMET
    amount: 1
    displayName: "&x&f&f&9&f&3&c&l▸ &x&6&b&e&e&7&cSiam Helmet &x&f&f&9&f&3&c&l◂"
    enchantments:
      - "PROTECTION_ENVIRONMENTAL:1"
    lore: []
  item_3:
    material: DIAMOND_CHESTPLATE
    slot: CHESTPLATE
    amount: 1
    displayName: "&x&f&f&9&f&3&c&l▸ &x&6&b&e&e&7&cSiam Chestplate &x&f&f&9&f&3&c&l◂"
    enchantments:
      - "PROTECTION_ENVIRONMENTAL:1"
    lore: []
  item_4:
    material: DIAMOND_LEGGINGS
    slot: LEGGINGS
    amount: 1
    displayName: "&x&f&f&9&f&3&c&l▸ &x&6&b&e&e&7&cSiam Leggings &x&f&f&9&f&3&c&l◂"
    enchantments:
      - "PROTECTION_ENVIRONMENTAL:1"
    lore: []
  item_5:
    material: DIAMOND_BOOTS
    slot: BOOTS
    amount: 1
    displayName: "&x&f&f&9&f&3&c&l▸ &x&6&b&e&e&7&cSiam Boots &x&f&f&9&f&3&c&l◂"
    enchantments:
      - "PROTECTION_ENVIRONMENTAL:1"
    lore: []


